name: documentation
on:
  push:
    branches:
      - master
    tags:
      - '!*' # Do not execute on tags
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master branch
      uses: actions/checkout@master

    - name: Build documentation and deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: docs
        BUILD_SCRIPT: yarn install && yarn docs
