name: pull-request-checks
on:
  pull_request:
    branches:
      - master
jobs:
  build-lint-test-checks:
    strategy:
      matrix:
        platform: [ 'ubuntu-latest' ]
        node: [ '12', '10', '8' ]
    name: checks/node ${{ matrix.node }}
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout master branch
      uses: actions/checkout@master
    - name: Install Node.js
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node }}
    - name: Install dependencies
      run: yarn install
    - name: Lint
      run: yarn lint && yarn lint:test
    - name: Build
      run: yarn build
    - name: Run tests
      run: yarn test
  coverage-check:
    needs: [ build-lint-test-checks ]
    name: coverage
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master branch
      uses: actions/checkout@master
    - name: Install Node.js
      uses: actions/setup-node@master
      with:
        version: '12'
    - name: Install dependencies
      run: yarn install
    - name: Build
      run: yarn build
    - name: Publish coverage report
      uses: paambaati/codeclimate-action@v2.2.0
      env:
        CC_TEST_REPORTER_ID: b565f7cd498145fafc38120f55678a656651299ce9371f87cf446ac20433196c
      with:
        coverageCommand: yarn coverage
